repos:
  - repo: local
    hooks:
      - id: precommit-fast
        name: make precommit-fast
        entry: make precommit-fast
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: prepush-full
        name: make prepush-full
        entry: make prepush-full
        language: system
        pass_filenames: false
        stages: [pre-push]
